### ISSUE TITLE
buttons are missing icon/text

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-react-examples#155]
many new samples are missing icons/images, e.g.

https://staging.infragistics.com/react-demos/samples/layouts/card-styling

https://staging.infragistics.com/react-demos/samples/layouts/card-overview
https://staging.infragistics.com/react-demos/samples/layouts/card-styling

https://staging.infragistics.com/react-demos/samples/grids/tree-basic-example

https://staging.infragistics.com/react-demos/samples/grids/list-overview

**Comment by agoldenbaum** [comment]
Fixed in this PR: https://github.com/IgniteUI/igniteui-react-examples/pull/255
