### ISSUE TITLE
slider sample throws errors

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-react-examples#179]
the slider-tick-labels sample throws errors and it does not render
https://staging.infragistics.com/react-demos/samples/inputs/slider-tick-labels

![image](https://user-images.githubusercontent.com/11665978/183487111-ba2008a6-0dcd-4bbf-8d24-2ace31fe4b1c.png)

**Comment by mddifilippo89** [comment]
logged internally as 274491

**Comment by mddifilippo89** [comment]
Added {-90} so the control renders, labels don't orient properly. 
https://github.com/IgniteUI/igniteui-react-examples/pull/181
