### ISSUE TITLE
slider sample has overlapping labels

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-react-examples#186]
slider sample has overlapping labels:
https://staging.infragistics.com/react-demos/samples/inputs/slider-value-format

![image](https://user-images.githubusercontent.com/11665978/189373025-761d5801-20f0-489e-9534-07fbb0c55d0c.png)

**Comment by mddifilippo89** [comment]
https://github.com/IgniteUI/igniteui-webcomponents/issues/554

**Comment by mddifilippo89** [comment]
occurs in webcomponents.

**Comment by HUSSAR-mtrela** [comment]
@mddifilippo89 please double interval between labels to 20

**Comment by mddifilippo89** [comment]
https://github.com/IgniteUI/igniteui-react-examples/pull/243
Not an actual issue, it happens in angular where this component was created from which if you shrink the width too much the labels will inevitable overlap.

https://www.infragistics.com/products/ignite-ui-angular/angular/components/slider/slider
