### ISSUE TITLE
React Updating Panes in Dock Manager Example does not show map 

### ISSUE THREAD

**Issue by IGvaleries** [IgniteUI/igniteui-react-examples#290]
goto 
https://www.infragistics.com/products/ignite-ui-react/react/components/layouts/dock-manager-updating-panes#react-updating-panes-in-dock-manager-example

in the bottom right pane, only the markers for the map are displayed, the background is missing

**Comment by HUSSAR-mtrela** [comment]
should be fixed on staging in the next build

**Comment by HUSSAR-mtrela** [comment]
fixed on production.
